In [3]:
import numpy as np
import pandas as pd

In [28]:
with open ('D:/Machine Learning/classroom/week2/vidu4_lin_reg.txt') as f:
    content = f.readlines()

content = [x.strip() for x in content]

In [29]:
content

['ID TUOI BMI HA GLUCOSE CHOLESTEROL BEDAYNTM',
 '1 56 21 160 14.0 6.00 1.95',
 '2 76 18 150 12.0 4.97 1.33',
 '3 63 16 160 4.4 6.39 .83',
 '4 78 20 100 4.0 7.00 2.00',
 '5 87 20 110 4.6 4.10 1.30',
 '6 76 19 150 4.6 2.74 1.16',
 '7 55 31 160 5.5 4.60 1.00',
 '8 74 22 100 6.8 5.04 1.00',
 '9 81 21 120 5.8 4.75 .80',
 '10 77 24 160 5.4 6.94 1.60',
 '11 29 20 120 3.8 4.84 .65',
 '12 71 22 160 3.3 6.63 1.00',
 '13 77 21 160 5.1 4.93 .97',
 '14 59 18 150 6.0 4.55 .73',
 '15 58 27 130 6.9 6.70 1.10',
 '16 34 19 130 4.5 3.20 1.10',
 '17 74 22 100 10.6 4.30 1.10',
 '18 61 19 170 18.0 6.80 .80',
 '19 53 20 130 25.0 5.50 .99',
 '20 65 28 140 6.5 6.80 1.00',
 '21 80 19 160 4.8 5.74 1.13',
 '22 71 25 160 6.2 6.90 1.00',
 '23 90 24 160 4.7 7.00 1.70',
 '24 44 24 120 6.0 3.40 .90',
 '25 91 27 150 6.1 4.92 .89',
 '26 75 22 160 6.2 6.08 .80',
 '27 60 24 140 4.7 6.25 .81',
 '28 51 22 150 4.8 5.40 1.20',
 '29 91 29 120 4.2 6.54 .82',
 '30 45 24 170 4.9 3.91 .89',
 '31 62 24 140 5.4 5.30 1.19',
 '32 65 

In [30]:
data = np.zeros((102,6),dtype=float)
index = 0
for i in content:
    if not i.startswith("I"):
        a = i.split(' ')
        data[index,:] = np.array([float(a[1]),float(a[2]),float(a[3]),float(a[4]),float(a[5]),float(a[6])])
    index += 1

In [31]:
data


array([[  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [ 56.  ,  21.  , 160.  ,  14.  ,   6.  ,   1.95],
       [ 76.  ,  18.  , 150.  ,  12.  ,   4.97,   1.33],
       [ 63.  ,  16.  , 160.  ,   4.4 ,   6.39,   0.83],
       [ 78.  ,  20.  , 100.  ,   4.  ,   7.  ,   2.  ],
       [ 87.  ,  20.  , 110.  ,   4.6 ,   4.1 ,   1.3 ],
       [ 76.  ,  19.  , 150.  ,   4.6 ,   2.74,   1.16],
       [ 55.  ,  31.  , 160.  ,   5.5 ,   4.6 ,   1.  ],
       [ 74.  ,  22.  , 100.  ,   6.8 ,   5.04,   1.  ],
       [ 81.  ,  21.  , 120.  ,   5.8 ,   4.75,   0.8 ],
       [ 77.  ,  24.  , 160.  ,   5.4 ,   6.94,   1.6 ],
       [ 29.  ,  20.  , 120.  ,   3.8 ,   4.84,   0.65],
       [ 71.  ,  22.  , 160.  ,   3.3 ,   6.63,   1.  ],
       [ 77.  ,  21.  , 160.  ,   5.1 ,   4.93,   0.97],
       [ 59.  ,  18.  , 150.  ,   6.  ,   4.55,   0.73],
       [ 58.  ,  27.  , 130.  ,   6.9 ,   6.7 ,   1.1 ],
       [ 34.  ,  19.  , 130.  ,   4.5 ,   3.2 ,   1.1 ],
       [ 74.  ,  22.  , 100.  ,

In [32]:
def deleteZeroRow(array):
    row_sums = array.sum(axis=1)
    zero_sum_rows = np.where(row_sums == 0)[0]
    array = np.delete(array, zero_sum_rows, axis=0)
    return array

In [33]:
data = deleteZeroRow(data)

In [34]:
data

array([[ 56.  ,  21.  , 160.  ,  14.  ,   6.  ,   1.95],
       [ 76.  ,  18.  , 150.  ,  12.  ,   4.97,   1.33],
       [ 63.  ,  16.  , 160.  ,   4.4 ,   6.39,   0.83],
       [ 78.  ,  20.  , 100.  ,   4.  ,   7.  ,   2.  ],
       [ 87.  ,  20.  , 110.  ,   4.6 ,   4.1 ,   1.3 ],
       [ 76.  ,  19.  , 150.  ,   4.6 ,   2.74,   1.16],
       [ 55.  ,  31.  , 160.  ,   5.5 ,   4.6 ,   1.  ],
       [ 74.  ,  22.  , 100.  ,   6.8 ,   5.04,   1.  ],
       [ 81.  ,  21.  , 120.  ,   5.8 ,   4.75,   0.8 ],
       [ 77.  ,  24.  , 160.  ,   5.4 ,   6.94,   1.6 ],
       [ 29.  ,  20.  , 120.  ,   3.8 ,   4.84,   0.65],
       [ 71.  ,  22.  , 160.  ,   3.3 ,   6.63,   1.  ],
       [ 77.  ,  21.  , 160.  ,   5.1 ,   4.93,   0.97],
       [ 59.  ,  18.  , 150.  ,   6.  ,   4.55,   0.73],
       [ 58.  ,  27.  , 130.  ,   6.9 ,   6.7 ,   1.1 ],
       [ 34.  ,  19.  , 130.  ,   4.5 ,   3.2 ,   1.1 ],
       [ 74.  ,  22.  , 100.  ,  10.6 ,   4.3 ,   1.1 ],
       [ 61.  ,  19.  , 170.  ,

In [10]:
headers = ['tuoi','bmi','ha','glucose','cholesterol','bedayntm']
df = pd.DataFrame(data,columns=headers)

In [11]:
y = df['bedayntm']
x = df[['tuoi','cholesterol','glucose','ha','bmi']]

In [12]:
x

tuoi  cholesterol  glucose     ha   bmi
0   56.0         6.00     14.0  160.0  21.0
1   76.0         4.97     12.0  150.0  18.0
2   63.0         6.39      4.4  160.0  16.0
3   78.0         7.00      4.0  100.0  20.0
4   87.0         4.10      4.6  110.0  20.0
..   ...          ...      ...    ...   ...
95  55.0         7.20      5.0  160.0  24.0
96  76.0         5.24      3.1  140.0  15.0
97  70.0         4.40      4.0  180.0  25.0
98  85.0         5.20      5.2  160.0  21.0
99  87.0         5.20      9.0  130.0  22.0

[100 rows x 5 columns]

In [13]:
data = x.to_numpy()
label = y.to_numpy()

In [14]:
from sklearn import linear_model

In [15]:
regr1 = linear_model.LinearRegression(fit_intercept=True)
regr1.fit(data,label)


LinearRegression()

In [16]:
print(regr1.coef_)

[ 0.00994694  0.03847025  0.0076701   0.00218137 -0.00020655]


# Chia dataset 80:20

In [17]:
x_train = x.loc[0:79]
x_test = x.loc[80:99]
y_train = y.loc[0:79]
y_test = y.loc[80:99]

In [18]:
x_train

tuoi  cholesterol  glucose     ha   bmi
0   56.0         6.00     14.0  160.0  21.0
1   76.0         4.97     12.0  150.0  18.0
2   63.0         6.39      4.4  160.0  16.0
3   78.0         7.00      4.0  100.0  20.0
4   87.0         4.10      4.6  110.0  20.0
..   ...          ...      ...    ...   ...
75  61.0         2.50      5.2  140.0  21.0
76  60.0         4.79     11.3  130.0  26.0
77  76.0         5.31      5.1  160.0  19.0
78  78.0         3.80      4.9  120.0  27.0
79  71.0         7.13      6.6  150.0  26.0

[80 rows x 5 columns]

In [19]:
x_train = x_train.to_numpy()
y_train = y_train.to_numpy()
x_test = x_test.to_numpy()
y_test = y_test.to_numpy()


In [20]:
regr2 = linear_model.LinearRegression(fit_intercept=True)
regr2.fit(x_train,y_train)

prediction = regr2.predict(x_test)

In [21]:
print(regr2.coef_)

[ 0.0089892   0.00708535  0.00808634  0.00260218 -0.00047742]


In [37]:
prediction

array([0.91012272, 0.78452963, 1.22339369, 0.96085817, 0.96836123,
       1.05009561, 1.19694736, 1.0521678 , 0.9936207 , 0.68503543,
       0.78429172, 0.77109845, 1.19748204, 1.06844174, 0.99721921,
       1.03380704, 1.14558205, 1.19228584, 1.29236178, 1.26252546])

In [42]:
print(np.var(prediction))

0.02951355036957152


In [54]:
print(np.std(prediction))

0.17179508249531336


In [38]:
summary = pd.DataFrame(prediction).describe()

In [51]:
summary

0
count  20.000000
mean    1.028511
std     0.176258
min     0.685035
25%     0.948174
50%     1.041951
75%     1.193451
max     1.292362

In [53]:
summary.loc['std']**2

0    0.031067
Name: std, dtype: float64